import fs from 'node:fs/promises';
const port=Number(process.argv[2]||42477);
class CDP{constructor(url){this.ws=new WebSocket(url);this.waiting=new Map();this.seq=0;this.events=[];this.ready=new Promise((r,j)=>{this.ws.onopen=r;this.ws.onerror=j});this.ws.onmessage=e=>{let d=JSON.parse(e.data);if(d.id){let p=this.waiting.get(d.id);this.waiting.delete(d.id);d.error?p.reject(d.error):p.resolve(d.result)}else this.events.push(d)}}async call(method,params={}){await this.ready;let id=++this.seq;return new Promise((resolve,reject)=>{this.waiting.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params}))})}close(){this.ws.close()}}
const targets=await(await fetch(`http://localhost:${port}/json`)).json();const target=targets.find(t=>t.id==='B4EE40FCDAFBE987B1E9C5C8D8226325')||targets.find(t=>t.url.includes('check=1'));if(!target)throw Error('Open a separate test tab with ?check=1');const c=new CDP(target.webSocketDebuggerUrl);
await c.call('Runtime.enable');await c.call('Page.enable');await c.call('Network.enable');
const url=new URL('./drone-autonomy-atlas.html?check=1', import.meta.url).href;await c.call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await c.call('Page.navigate',{url});
async function evalJS(expression){const r=await c.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value}
for(let i=0;i<40;i++){let ok=await evalJS('typeof D!=="undefined" && !!document.querySelector(".graph-node")');if(ok)break;await new Promise(r=>setTimeout(r,80))}
await evalJS('document.fonts.ready');const tests=[];function check(name,v){tests.push({name,pass:!!v});if(!v)throw new Error(name)}
check('Data and default graph load',await evalJS('D.projects.length===143 && state.selected==="fastdrone" && document.querySelectorAll(".graph-node").length>1'));
check('All projects render and graph labels stay within node boxes',await evalJS(`(()=>{let fail=[];for(const p of D.projects){state.selected=p.id;state.mapMode='focus';state.edgePage=0;render();if(!document.querySelector('.graph-node'))fail.push(p.id);for(const t of document.querySelectorAll('.node-title,.node-role'))if(t.getBBox().width>198)fail.push(p.id+':wide text:'+t.textContent)}return fail.length?fail:false})()` )===false);
await evalJS("navigate('map','px4')");check('Neighbor pagination exists',await evalJS('document.querySelector("[data-graph-page=\\"1\\"]")!==null'));
await evalJS("document.querySelector('[data-graph-page=\"1\"]').click()");check('Neighbor pagination works',await evalJS('state.edgePage===1'));
await evalJS("navigate('map','fastdrone');document.querySelector('.graph-edge').dispatchEvent(new MouseEvent('click',{bubbles:true}))");check('Edge opens sourced explanation',await evalJS('document.querySelector("#dialog").open && !!document.querySelector("#dialog-body a[href^=https]")'));await evalJS("document.querySelector('#dialog .close').click()");
await evalJS("document.querySelector('[data-project=\"vins\"]').dispatchEvent(new MouseEvent('click',{bubbles:true}))");check('Clicking a graph project follows connection',await evalJS('state.selected==="vins"'));
await evalJS("document.querySelector('[data-inspect-tab=\"sources\"]').click()");check('Sources panel contains repository',await evalJS('!!document.querySelector(".inspect-body a[href*=VINS-Fusion]")'));
await evalJS("state.compare=[];toggleCompare('cerlab');toggleCompare('mrs');toggleCompare('ntnu');toggleCompare('fastdrone');toggleCompare('px4')");check('Comparison limit is four',await evalJS('state.compare.length===4 && !state.compare.includes("px4")'));await evalJS("navigate('compare')");check('Comparison columns render',await evalJS('document.querySelectorAll(".compare-table thead th").length===5'));
await evalJS("document.querySelector('[data-compare=\"mrs\"]').click()");check('Comparison removal works',await evalJS('state.compare.length===3'));
await evalJS("navigate('catalogue');state.query='LiDAR';state.layer='Perception';render()");check('Combined catalogue filters work',await evalJS('filteredProjects().length>0 && filteredProjects().every(p=>p.layer==="Perception")'));
await evalJS("state.query='zzzz-not-a-project';render()");check('Catalogue empty state',await evalJS('!!document.querySelector(".empty")'));await evalJS('resetFilters()');check('Catalogue reset and pagination',await evalJS('filteredProjects().length===143 && document.querySelectorAll(".catalog-row").length===22'));
await evalJS("document.querySelector('[data-cat-page=\"1\"]').click()");check('Catalogue pagination advances',await evalJS('state.catPage===1'));
await evalJS("navigate('audit');state.claimVerdict='Contradicted / outdated';render()");check('Contradiction filter finds three checks',await evalJS('document.querySelectorAll(".claim").length===3'));
await evalJS("document.querySelector('#audit-expand').click()");check('Claim expansion',await evalJS('[...document.querySelectorAll(".claim")].every(e=>e.open)'));
await evalJS("openClaim('C26')");check('Direct claim links open correct check',await evalJS('document.querySelector("#claim-C26").open'));
await evalJS("navigate('directions');document.querySelector('[data-direction=\"learning\"]').click()");check('Starting point selection',await evalJS('state.direction==="learning" && document.body.innerText.includes("RAPPIDS")'));
await evalJS("document.querySelector('#compare-direction').click()");check('Compare starting points action',await evalJS('state.view==="compare" && state.compare.length===4'));
await evalJS("navigate('evidence')");check('Methodology counts',await evalJS('document.body.innerText.includes(String(D.method.exaSearches)) && document.body.innerText.includes(String(D.method.uniqueDiscoveryURLs))'));
await evalJS("navigate('map','fastdrone');document.querySelector('#global-search').value='NanoMap';document.querySelector('#global-search').dispatchEvent(new Event('input',{bubbles:true}))");check('Global search includes full catalogue',await evalJS('document.querySelector("#search-results").innerText.includes("NanoMap")'));await evalJS("document.querySelector('#search-results button').click();document.querySelector('#global-search').value='';document.querySelector('#search-results').hidden=true");check('Search selection opens project',await evalJS('state.selected==="nanomap"'));
await evalJS("navigate('map','fastdrone');window.scrollTo(0,0)");
async function screenshot(name,w,h){await c.call('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:w<500});await evalJS('window.scrollTo(0,0);document.querySelector("#toast").hidden=true;document.fonts.ready');const shot=await c.call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile('research/atlas/'+name+'.png',Buffer.from(shot.data,'base64'))}
await screenshot('preview-desktop',1440,1000);check('Desktop no page-level overflow',await evalJS('document.documentElement.scrollWidth<=innerWidth'));
await screenshot('preview-mobile',390,844);check('Mobile no page-level overflow',await evalJS('document.documentElement.scrollWidth<=innerWidth'));
for(const view of ['catalogue','audit','directions','compare','evidence']){await evalJS(`navigate('${view}')`);check('Mobile overflow: '+view,await evalJS('document.documentElement.scrollWidth<=innerWidth'))}
await evalJS("navigate('audit');openClaim('C07');window.scrollTo(0,0)");await screenshot('preview-audit',1440,1000);
await evalJS("state.compare=['cerlab','mrs','ntnu','fastdrone'];navigate('compare')");await screenshot('preview-compare',1440,1000);
const errors=c.events.filter(e=>e.method==='Runtime.exceptionThrown');check('No runtime exceptions',errors.length===0);
const network=c.events.filter(e=>e.method==='Network.requestWillBeSent').map(e=>e.params.request.url).filter(u=>u.startsWith('http'));check('Atlas requires no network requests',network.length===0);
await fs.writeFile('research/atlas/browser-checks.json',JSON.stringify({tests,errors,network},null,2));console.log(JSON.stringify({passed:tests.length,total:tests.length,errors,network},null,2));c.close();
